/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 statistic_charts_with_arrow.gltf --transform
Author: cig3d (https://sketchfab.com/cig3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/statistic-charts-with-arrow-86f9238bdaf44e098b6da4d82ee1861f
Title: Statistic Charts With Arrow
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/statistic_charts_with_arrow-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.002']} position={[-0.25, 0, 0]} scale={[0.32, 0.32, 0.28]} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials['Material.003']} position={[0.61, 0, 0]} scale={[0.32, 0.32, 0.53]} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials['Material.004']} position={[1.44, 0, 0]} scale={[0.32, 0.32, 0.78]} />
        <mesh geometry={nodes.Cube003_0.geometry} material={materials['Material.001']} position={[-1.48, -0.05, 0.21]} rotation={[0, 0.57, 0]} scale={[0.09, 0.07, 0.58]} />
      </group>
    </group>
  )
}

useGLTF.preload('/statistic_charts_with_arrow-transformed.glb')
