/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 wd_green_1tb_hard_disk_hdd.gltf --transform
Author: MG990 (https://sketchfab.com/MG990)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wd-green-1tb-hard-disk-hdd-e9244f56e0724dd097570e29bae4b7c6
Title: WD Green 1TB Hard Disk HDD
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/wd_green_1tb_hard_disk_hdd-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.02, 0.35, 0]}>
        <mesh geometry={nodes.Object_12.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_0} />
      </group>
      <group position={[0.02, 0.38, 0]}>
        <mesh geometry={nodes.Object_23.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.metal} />
      </group>
      <group position={[1.18, 0.6, -2.22]} scale={0.1}>
        <mesh geometry={nodes.Object_31.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.material_0} />
      </group>
      <group position={[1.62, 0.6, 0.11]} scale={0.1}>
        <mesh geometry={nodes.Object_34.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.material_0} />
      </group>
      <group position={[1.55, 0.6, 2.28]} scale={0.1}>
        <mesh geometry={nodes.Object_37.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} />
      </group>
      <group position={[1.55, 0.12, 1.49]} rotation={[0, 0, -Math.PI]} scale={[-0.1, 0.1, 0.1]}>
        <mesh geometry={nodes.Object_48.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.material_0} />
      </group>
      <group position={[0.62, 0.13, 1.89]} rotation={[0, 0, -Math.PI]} scale={[-0.1, 0.1, 0.1]}>
        <mesh geometry={nodes.Object_51.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} />
      </group>
      <group position={[-1.44, 0.12, 1.72]} rotation={[0, 0, -Math.PI]} scale={[-0.1, 0.1, 0.1]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.material_0} />
      </group>
      <group position={[1.05, 0.12, 0.16]} rotation={[0, 0, -Math.PI]} scale={[-0.1, 0.1, 0.1]}>
        <mesh geometry={nodes.Object_57.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.black} position={[-0.06, 0.68, 1.93]} scale={0.28} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.black} position={[-1.43, 0.68, 2.2]} scale={0.28} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.black} position={[-1.42, 0.68, 0.78]} scale={0.28} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.black} position={[-1.33, 0.68, -1.9]} scale={0.28} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.gray_plastic} position={[-1.63, 0.13, 2.41]} rotation={[-Math.PI, 0, 0]} scale={[-0.09, 0.09, 0.09]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.gray_plastic} position={[-1.44, 0.08, 2.4]} scale={[0.01, 0.01, 0.1]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.gray_plastic} position={[1.21, 0.08, 2.4]} scale={[-0.01, 0.01, 0.1]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.gold} position={[0.81, 0.16, 2.43]} scale={[0.01, 0.01, 0.07]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.gold} position={[-0.81, 0.08, 2.36]} scale={[0.02, 0.01, 0.13]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.gold} position={[0.13, 0.08, 2.36]} scale={[0.02, 0.01, 0.13]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.black} position={[1.69, 0.09, 0.98]} scale={0.07} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.black} position={[1.69, 0.09, -0.47]} scale={0.08} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.black} position={[-1.65, 0.09, -0.64]} scale={0.08} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.black} position={[-1.65, 0.09, 0.62]} scale={0.08} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.metal} position={[1.73, 0.13, 1.82]} rotation={[0, 0, -Math.PI / 2]} scale={0.04} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.metal} position={[1.73, 0.13, 0.1]} rotation={[0, 0, -Math.PI / 2]} scale={0.04} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.metal} position={[1.73, 0.13, -1.97]} rotation={[0, 0, -Math.PI / 2]} scale={0.04} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.metal} position={[1.78, 0.25, -0.6]} scale={1.42} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.chip} position={[0.28, 0.05, 1.21]} rotation={[0, 0, Math.PI]} scale={1.51} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['wd1tb-green']} position={[0.02, 0.73, -0.17]} scale={3.56} />
    </group>
  )
}

useGLTF.preload('/wd_green_1tb_hard_disk_hdd-transformed.glb')
